### ISSUE TITLE
Perfeccionamiento movimiento del personaje

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#12]
Personaje:
- El personaje prácticamente vuela, no tiene definido un limete de altura.
- Al caer baja a una velocidad muy lenta.
- Se destabiliza al chocar contra algo. Definir fisica.

Tiempo Estimado: 5 h
Tiempo Real: (1) h

Criterios de aceptación:
- [x] Tiene un salto correcto.
- [x] Cae a una velocidad considerable.
- [x] No se destabiliza.

**Comment by ghost** [comment]
https://unity3d.com/es/learn/tutorials/topics/2d-game-creation/2d-character-controllers

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=4hIVBYgXnFQ

**Comment by Jromaa** [comment]
@staskbieto He indicado el plazo máximo y los criterios de aceptación de esta issue.
