### ISSUE TITLE
Colocar Collider  2D en los objetos del mapa.

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#13]
Colocar Collider2D en los suelos y objetos en el mapa para que el personaje no las pueda traspasar.

Tiempo Estimado:  1h
Tiempo Real:  1h
Plazo máximo: 29 de octubre

Criterios de aceptación:
- [x] Todos los GameObject que corresponden al suelo tiene que tener Collider2D.

**Comment by Jromaa** [comment]
@catiza2003 He indicado el plazo máximo y los criterios de aceptación de esta issue.
