### ISSUE TITLE
Ordenación nombres y asignar un TAG a los GameObjects

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#14]
Ordenar jerarquicamente los nombres de los GameObjects y asignar a cada uno un TAG (nombre que lo describa).
Ej: GameObject cazador tendrá el TAG player.
     GameObject del fondo del mapa tendrá el TAG backgroung.

Tiempo Estimado:  1h
Tiempo Real:  2h
Plazo máximo: 29 de Octubre

Criterios de aceptación:
- [x] Ordenar jerarquicamente, si se cree conveniente los GameObject.
- [x] Colocar a los GameObject un TAG, que describa que es.

**Comment by Jromaa** [comment]
@catiza2003  He indicado el plazo máximo y los criterios de aceptación de esta issue. También he añadido otra tarea que es colocar un TAG a los GameObject, como te lo comenté hoy en clase.

**Comment by ghost** [comment]
A los animales le pondremos TAG Animal, y a los cazadores Hunter
