### ISSUE TITLE
Refactorizar proyecto [merged master]

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#15]
Limpiar datos innecesarios del proyecto principal.

Criterios de aceptación:
- [x] Proyecto limpio de datos innecesarios.

Tiempo estimado: 1h
Tiempo realizado: 1h 30 min

**Comment by ghost** [comment]
~~Algo ha fallado en la refactorización. He clonado el repositorio y no se abre. He hecho
git checkout 0364c2a2184c487a624d21141b6b58f4b8046cbf -- Assets\
¡Y si funciona! Hay que revisar el commit y arreglarlo. Te lo miras tú @RokaZetsu ?~~
