### ISSUE TITLE
Diagrama de classes [merged master]

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#16]
Diseñar el diagrama de clases para la realización del código del juego.

Tiempo Estimado:  2,5h
Tiempo Real:  h

**Comment by ghost** [comment]
Me pongo con esto

**Comment by ghost** [comment]
Primer boceto muy básico

![img_20171025_211557_062](https://user-images.githubusercontent.com/26376503/32018399-0cbaa436-b9ca-11e7-9297-fae003e17e12.jpg)
