### ISSUE TITLE
Dissenyo de barra de vida.

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#18]
Diseñar varias barras de vida. Una que corresponda al 100%, 90%, 80%, ..., hasta 0%.
Tiempo Estimado: 1 h
Tiempo Real:  1h

Criterios de aceptación:
- [x] Diseño de la barra de vida de 100% y 0%

**Comment by Jromaa** [comment]
@adria88  He indicado el plazo máximo y los criterios de aceptación de esta issue.
