### ISSUE TITLE
Dissenyo barra de stamina

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#19]
Diseñar una barra de stamina. Queda por determinar la cantidad que gasta cada ataque. Por el momento lo ideal seria tener una barra de stamina al 100% y otra al 0%.

Tiempo Estimado: 1h
Tiempo Real: 1h

Criterios de aceptación:
- [x] Barra de stamina la 100% y al 0%.

**Comment by Jromaa** [comment]
@adria88 He indicado el plazo máximo y los criterios de aceptación de esta issue.
