### ISSUE TITLE
Barra de stamina

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#21]
Programar script para la barra de stamina.

Tiempo Estimado: h
Tiempo Real: h

Criterios de aceptación:
- [x] Crear barra de stamina para el jugador.

**Comment by ghost** [comment]
Se le tiene que asociar un cuadradito con la vida y la estamina a los personajes creados des de la clase Equipo. Los valor que se visualicen se gestinaran des de la clase Jugador

**Comment by MichaelShakke** [comment]
Start 29/11/17 - End 30/11/17
1h
