### ISSUE TITLE
Acción disparar.

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#27]
Hacer que el persoanje pueda disparar y quitar vida.
Tiempo Estimado: 8h
Tiempo Real: ( 3h pol) h 9h(mich)
Criterios de aceptación:
- [x] Con la tecla Enter permita disparar

**Comment by ghost** [comment]
+Crear clase arma
+Referencia de arma en Equipo
+Equipo le pasa el arma a Jugador 
+Jugador, al hacer click izquierdo llama al método disparar de la clase Arma.
+El método disparar de la clase Arma le da velocidad al gameobject asociado para generar la trayectória.
+El método update de Arma, controla el impacto del arma con el resto de gameobjects y otros obstaculos, y actua en consecuéncia (disminuir vida, destruir trozo de terreno etc)

**Comment by MichaelShakke** [comment]
Start 10/11/17 - End 27/11/17
9h
