### ISSUE TITLE
Opciones de menu.

### ISSUE THREAD

**Issue by AntRocIOT** [EnginyeriaSofwareUB/ES2017B1#30]
Sonido del juego al vover al menu opciones.
Implementar funcionalidad pantalla completa.

Tiempo Estimado: 4h
Tiempo Real:  4h

Criterios de aceptación:
- [x] Sonido funciona al cambiar de escena.
- [x] Funcionalidad de la pantalla completa.

**Comment by Jromaa** [comment]
Falta que quan es torni a opcions mantingui el so.

**Comment by Jromaa** [comment]
Sonido funciona correctamente en las diferentes escenas. 
Se puede poner el juego en pantalla completa o desactivarla.
