### ISSUE TITLE
Integrar Animaciones del personaje con código de jugador y código de cambiar turno

### ISSUE THREAD

**Issue by catiza2003** [EnginyeriaSofwareUB/ES2017B1#37]
- Arreglar que las animaciones de los personajes concuerden con los movimientos de saltar , caminar y estar de pie (Idle) , cambio de turno.

**Comment by ghost** [comment]
Se tienen que crear los personajes de manera programática des de la clase Equipos, y ahí, distribuirlos en els escenario de forma aleatória.

**Comment by Jromaa** [comment]
Ja està fet.
