### ISSUE TITLE
Relacionar script disparo con script barra de estamina y barra de vida

### ISSUE THREAD

**Issue by catiza2003** [EnginyeriaSofwareUB/ES2017B1#42]

**Comment by ghost** [comment]
A tener en cuenta:

- [x] Crear clase arma

- [x] Equipo tiene una LISTA de armas. Cuando se llame el método start, poner un objeto arma cómo mínimo (siempre tienen una arma, la básica).

- [x] Crear referencia de la clase arma en Jugador. Cuando des de equipo escojamos el ACTUAL_PLAYER, le pasamos el arma del equipo (setArma = armaactual)

- [x] Crear modos apuntar y disparo en Jugador. 

- [x] Crear método disparar en la clase Arma. El update() de arma irá comrpobando las posibles colisiones.

**Comment by MichaelShakke** [comment]
Start 29/11/17 - End 30/11/17
1h
