### ISSUE TITLE
Afinar salto del personaje

### ISSUE THREAD

**Issue by catiza2003** [EnginyeriaSofwareUB/ES2017B1#50]
Ell salto que no sea como volando, que haga un salto en curva equilibrado y limitado , que no atraviese los muros cuando salta.
Tiempo Estimado:2 h
Tiempo Real:3 h
Criterios de aceptación:
- [x] Implementar el salto de manera correcta
- [x] No atraviesa muros
- [ ] Salto curvado.

**Comment by ghost** [comment]
Ahora mismo lo hace con fuerza y sin gravedad...

Pensar en otra manera si no se puede afinar.

Saltos finitos. Durante un salto no se puede volver a saltar. 

Salto en arco... Lo hacemos según esté a derecha o izquierda?
