### ISSUE TITLE
Integrar Cajas sorpresa en el juego

### ISSUE THREAD

**Issue by catiza2003** [EnginyeriaSofwareUB/ES2017B1#52]
Aparecen cajas cayendo de forma aleatoria en el mapa. En este Sprint las cajas pueden tener:
- gana estamina
- gana vida 
- pierde turno

Tiempo estimado: 6h
Tiempo real: 10h

Criterios de aceptación:
- [x] Cajan caen aleatoriamente por el mapa.
- [x] Personaje gana estamina.
- [x] Personaje gana vida.

**Comment by Jromaa** [comment]
Faltaria comprobar que el jugador gana/pierde estamina/vida. El cambio si que lo realiza correctamente.
