### ISSUE TITLE
Cambio de escena de la pantalla principal

### ISSUE THREAD

**Issue by Jromaa** [EnginyeriaSofwareUB/ES2017B1#6]
Se tiene que hacer el cambio de escena cuando se presione cualquier botón del menú principal.
Botones:
- Jugar
- Opciones
- Salir -> Implementar que se salga del juego.
Para los botones Jugar y Opciones, cambiar a dos escenas distintas.

Tiempo estimado: 2h

Realizado:
- [x] Cambio de escena de Jugar
- [x] Cambio de escena de Opciones
- [x] Salir del juego

**Comment by AntRocIOT** [comment]
Necesito saber los numeros de las scenes.

**Comment by Jromaa** [comment]
De momento creo que solo habría 3, la del menú principal, la de opciones y la del mapa del juego

**Comment by ghost** [comment]
Está en la wiki bien detallado!
