### ISSUE TITLE
Finalizar las accciones de la pantalla de settings

### ISSUE THREAD

**Issue by adria88** [EnginyeriaSofwareUB/ES2017B1#77]
Criterios de aceptación:
- [x] Cambiar la imagen de off a on al pulsar.
- [x] Cambiar la imagen de off a on pantalla completa.
- [x] Al pulsar musica , mutear musica del juego
- [x] Al pulsar sonido , mutear los sonidos del juego.

Horas de trabajo:
- Previsión: 2h
- Realidad: 2h 30min

Fecha límite:
- **8/12/2017**

**Comment by Jromaa** [comment]
Falta que @adria88  ponga la imagen de desactivación de pantalla completa.
