### ISSUE TITLE
Funcionalidades de los dos roles

### ISSUE THREAD

**Issue by adria88** [EnginyeriaSofwareUB/ES2017B1#95]
RAMA Feature-95
Criterios de aceptación:

- [x] Aplicar el logo de cada rol a la izquierda de las barras(vida y estamina).

- [x] Comprobar que los dos roles actuan correctamente.

Horas de trabajo:
- Previsión: 4h
- Realidad: 2h

**Comment by ghost** [comment]
Los iconos deberían ponerse en makeAgile y makeDestructor, en jugador, y después tratarlo cómo las barras
